### PR TITLE
DeCovid app

### PR DESCRIPTION
**Pull request by cameronaaron**
Hi all,

Due to Google regulations we have decided to brand ourselves a bit more generally. We are going to try to back away from using C19 and Covid 19  as this keeps getting flaged as not being sensitive

"During review, we found that your app violates the Sensitive Events policy. Specifically, we don't allow apps that lack reasonable sensitivity towards or capitalize on a natural disaster, atrocity, conflict, death, or other tragic event.

You can read through the Sensitive Events page for more details.

For example, your app currently contains references related to the Coronavirus (COVID-19) pandemic."

Please give your ideas below

### CODE REVIEW

**Comment by cameronaaron** [comment]
Screen Shot 2020-04-28 at 1 27 44 PM

**Comment by cameronaaron** [comment]
@Riz-waan Do you think we need to change the package name as well or na?

**Comment by Riz-waan** [comment]
@cameronaaron I am not sure if we need to but we might have to, whats our decovid name?

**Comment by cameronaaron** [comment]
Just bayshield

**Comment by Riz-waan** [comment]
@cameronaaron I don't know if that is necessary because by standard our package name should start with org.c19bayshield so I mean we could change it to org.c19bayshield.bayshield?

**Comment by cameronaaron** [comment]
I feel that could be ok we can try that

**Comment by Kthulu120** [comment]
I would do what @Riz-waan suggested, BayShield should be fine since your working directly with institutions and this app is meant for those places. So I think it matters less so if the app has Covid19 in the name since people who want to find the app will be specifically looking for it.

**Review by Kthulu120 — APPROVED** [review]

**Comment by Kthulu120** [comment]
Also 2 reviews seem like a bit much for such as lean project so I think one approval should be fine @cameronaaron

**Pull request merged**
