### PR TITLE
Collection Hub Landing Page

### LINKED ISSUE #44: Collection Hub Landing Page
Incoming are items that are being delivered from makers.

Pending are the orders that are assigned to this hub to be delivered to medical orgs.

Delivered number displayed how many PPE they have distributed so far.

Inventory takes them to the tab where they can look at the count.

Add one of these labels:
- Very Urgent

Frame 28

### PR DESCRIPTION
**Pull request by emily-zhu**
Overview: Created hub landing page, with ability to navigate between screens.

SCREENCAST: https://drive.google.com/file/d/14hFWT4lKzbYnqkm7CgLX6XxKpTomw2Bt/view?usp=sharing
Screen Shot 2020-05-28 at 10 46 03 PM
Screen Shot 2020-05-28 at 10 46 10 PM
Screen Shot 2020-05-28 at 10 46 18 PM

Edited screens:
• `hub_screen`: displays the home screen, orders screen, profile screen

New widgets:
• `MainAppBar`: application bar with Bayshield logo + logout button
• `UserTypeTag`: peach-colored tag that displays the user type (Maker, Medical Facility, Collection Hub)
• `AlertTag`: blue-grey tag that displays any alerts for the user
• `IncomingItemsCard`: displays # of incoming items
• `PendingItemsCard`: displays # of pending items
• `ShippedItemsCard`: displays # of shipped items
• `InventoryButton`: button titled "Inventory" that redirects to the inventory tab on the Profiles page
• `MainBottomNavigationBar`: bottom navigation bar with the three icons - Orders, Home, Profile **_(TODO: change settings logo to new profile logo)_**

New assets (4):
• home.png, orders.png, settings.png, logo.png

### CODE REVIEW

**Comment by Riz-waan** [comment]
Hey Emily, All looks good, but what do you think about adding padding in the following places below?

Screen Shot 2020-05-29 at 1 51 18 AM
Screen Shot 2020-05-29 at 1 51 30 AM

What do you think @tinataleb

**Comment by emily-zhu** [comment]
@Riz-waan That's just there for placeholder right now! To show change for moving between the tabs. I set up the basic logic there so that it's easier to implement actual content later :)

**Review by Riz-waan — DISMISSED** [review]
Alright, that sounds good!

**Review by shalandy — DISMISSED** [review]
just tested and lgtm! go ahead and merge and I'll deal with the landing page code merge conflicts (I think there might be some in widgets.dart) later

**Review by Riz-waan — DISMISSED** [review]

**Review by shalandy — DISMISSED** [review]

**Review by Riz-waan — APPROVED** [review]

**Review by shalandy — APPROVED** [review]

**Pull request merged**
