### PR TITLE
landing page redesign according to figma ver1.1

### LINKED ISSUE #18: Landing Page
After user downloads and opens the app they will see a welcome message and button to **Sign Up** or **Log in**.

### PR DESCRIPTION
**Pull request by shalandy**
> Note: full name not registered into signup process yet

differences from figma:
- changed _Log in now_ to _Sign in now_ for consistency
- kept icons and consistent form fields between two pages
signin
signup

### CODE REVIEW

**Comment by emily-zhu** [comment]
Sign-in works fine! but when I try to sign up I get this error. :( I also tried multiple different emails.
Screen Shot 2020-05-28 at 10 41 10 PM

**Comment by shalandy** [comment]
@emily-zhu ah yes the name entry was saved to email—thanks for testing!

**Review by Riz-waan — APPROVED** [review]
I haven't run it, but I just took a look at the code and everything seems fine

**Comment by emily-zhu** [comment]
sign in / sign up lgtm! 
when i get to filling in info, there's an overflow error, and also the input text seems to be white? not sure if that's just something weird on my end

Screen Shot 2020-05-29 at 8 43 12 PM

**Review by cameronaaron — APPROVED** [review]

**Pull request merged**
